# Generated by Django 4.2.2 on 2023-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
