# Generated by Django 4.2.2 on 2023-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.TextField(default=models.CharField(max_length=1000)),
        ),
    ]
