# Generated by Django 4.2.2 on 2023-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(default=models.CharField(max_length=1000), max_length=500),
        ),
    ]
