# Generated by Django 4.2.2 on 2023-07-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_events_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribedToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_user_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('event', models.ManyToManyField(to='main.events')),
            ],
        ),
    ]
