# Generated by Django 4.2.2 on 2023-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subscribedtoevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribedToEvent',
            new_name='SubscribeToEvent',
        ),
        migrations.AddField(
            model_name='events',
            name='event_email',
            field=models.BooleanField(default=False),
        ),
    ]
