# Generated by Django 4.2.2 on 2023-07-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_subscribedtoevent_subscribetoevent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_status',
            new_name='event_status_to_come',
        ),
    ]
