# Generated by Django 4.2.2 on 2023-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_testimonies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahnazImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Mahnaz')),
                ('image_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OurImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Our_works')),
                ('img_name', models.CharField(max_length=20)),
            ],
        ),
    ]
