# Generated by Django 4.2.2 on 2023-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mahnazimages_ourimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='default.png', upload_to='events'),
        ),
    ]
