# Generated by Django 4.2.2 on 2023-07-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_events_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
