# Generated by Django 4.2.2 on 2023-07-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_events_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonies',
            name='image',
            field=models.ImageField(default='default.png', upload_to='testimonies/'),
        ),
    ]
