# Generated by Django 4.2.2 on 2023-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_testimonies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_email',
            field=models.BooleanField(default=True),
        ),
    ]
