# Generated by Django 4.2.2 on 2023-07-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahnazimages',
            options={'verbose_name': 'Images Of Mahnaz'},
        ),
    ]
