# Generated by Django 4.2.2 on 2023-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_mahnazimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='ourimages',
            options={'verbose_name': 'Our Image'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribed User'},
        ),
        migrations.AlterModelOptions(
            name='subscribetoevent',
            options={'verbose_name': 'Event Subscription'},
        ),
        migrations.AlterModelOptions(
            name='testimonies',
            options={'verbose_name': 'Testimony'},
        ),
    ]
