# Generated by Django 4.2.2 on 2023-07-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_frequentquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentquestions',
            options={'verbose_name': 'Add faq'},
        ),
    ]
