# Generated by Django 4.2.2 on 2023-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_frequentquestions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='online_venu',
            field=models.URLField(null=True),
        ),
    ]
