# Generated by Django 4.2.2 on 2023-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_events_online_status_events_online_venu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='online_status',
            field=models.BooleanField(default=False, verbose_name='Thick if its webinar'),
        ),
    ]
