# Generated by Django 4.2.2 on 2023-08-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_events_online_venu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='default.webp', upload_to='events'),
        ),
    ]
