# Generated by Django 4.2.2 on 2023-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_events_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_blog',
            field=models.CharField(default='Art', max_length=300),
        ),
    ]
