# Generated by Django 4.2.2 on 2023-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_post_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.AddField(
            model_name='post',
            name='image_blog',
            field=models.ImageField(default='default.png', upload_to='blog'),
        ),
    ]
