# Generated by Django 4.2.2 on 2023-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_post_image1_post_image_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='online_status',
            field=models.IntegerField(choices=[(0, 'Physical'), (1, 'Online')], default=0, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='events',
            name='online_venu',
            field=models.URLField(blank=True, help_text='Link to webinar', null=True, verbose_name='Webinar'),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
