# Generated by Django 4.2.2 on 2023-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_events_online_status_alter_events_online_venu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='online_status',
            field=models.IntegerField(choices=[(0, 'Physical'), (1, 'Online')], default=0, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='events',
            name='online_venu',
            field=models.URLField(blank=True, help_text='Link To Webinar', null=True, verbose_name='Webinar'),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Physical Location'),
        ),
    ]
