# Generated by Django 4.2.2 on 2023-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_events_online_venu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahnazContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook Profile Link')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Profile Link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Profile Link')),
                ('skype', models.URLField(blank=True, null=True, verbose_name='Skype Profile Link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile Link')),
                ('phone', models.IntegerField(blank=True, help_text='Add country Code', null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
