# Generated by Django 4.2.2 on 2023-09-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_mahnazcontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahnazcontacts',
            options={'verbose_name': 'Add Contact Info'},
        ),
    ]
