# Generated by Django 4.2.2 on 2023-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_mahnazcontacts_country_mahnazcontacts_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahnazcontacts',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='Tiktok Profile Link'),
        ),
    ]
